### ISSUE TITLE
Gary Tasks Due Week 11

### ISSUE THREAD

**Issue by NinaTanneberger** [rhaubt/rockartdatabase_v3#66]
Continue working on your templates - Company & Profile

**Comment by GaryLamKa** [comment]
Just uploaded the page in class, for the profile page, there are four section: User Information/ Company Information, Recent activity, Feature Content and User's Map. 

For the User/ Company Information, **MUST** have "Name", "Photo" and "Bio", and then few more we can put in "Website" (It can be personal website or other rock art website that they are Admin or member), "Profession", "Education Level", "Talk/ Discussion" and "Social Media", however, it less important because it same reason with wikipedia user that person won't want to put too much personal information. My understand with the Company page is for rock art researcher from a company/ school or other rock art website member or admin, because they want to put their rock art into the our website. Therefore, on the company page, there will be a "Admin" display and no talk/ discussion button, so they just talk to the admin, which back to the user profile page. 

For the "Recent Activity" and "Feature Content", it the key content to display, the propose of that is that when people click into the profile, they can know about that what the user is working on "Recent Activity" and what the user participate with "Feature Content". The reason for that is one rock art post can be edit by a lot of people, and the contribute can be count with % of the work load, as if the contribute with the rock art post is above a like 15% or 25%, they can claim that in their "Feature Content". "Recent Activity" there is some number button is not working and we need to work on later, it work as a page thing that if people wanna see more history of the user activity. 

For the "User's Map", is just a overall that the user contributed with and show it in the map. 

Lastly, there is some extra stuff can be add in if we finish the important part: subscribe to the user/ company (followers), trophy (https://en.wikipedia.org/wiki/User:AnomieBOT#Barnstars_and_other_rewards) and Talk page. Also there is a different way to do the whole thing I may want to try.(https://en.wikipedia.org/wiki/Wikipedia:Today%27s_articles_for_improvement)
It will only display the part you want to see (Main page, Articles for improvement, Article nominations, but as User Information/ Company Information, Recent activity, Feature Content and User's Map)

To Do List: for next week: Finish the page with all the important part, Parameters/ Info box, Image display and the map

**Comment by GaryLamKa** [comment]
Added a test page in the sitePages file, included the template in the page.
1. Create three Template page, with the " Template: " + "Namespace " on the URL (There is two profile page inside the profile)
2. Create the TestPage without putting " Template: " on the URL
