### ISSUE TITLE
Progress Update

### ISSUE THREAD

**Issue by NinaTanneberger** [rhaubt/rockartdatabase_v3#71]
Can you all please comment with your progress this week so we all know where we are at with the project.

@GaryLamKa @jbren48 I've heard almost nothing from you this week. What's happening?

**Comment by NinaTanneberger** [comment]
Spent most of the week troubleshooting the MediaWiki install. I need feedback from the rest of the group with what is happening there. It works on three of my machines but won't work on Jackson's.

Have only just started playing with the MediaWiki templates but I am seeing a fair few problems already. My focus is going to be on user interface because I am coming into it blind whereas you guys are already familiar with it.

**Comment by JacksonGartner** [comment]
I've been troubleshooting the install_v4 issue with you.
In terms of the home page, with no solution being found by the team or @rhaubt I've resorted to a plain background and without images there has been little change as I've been following the `Mock_Home2.png` mock-up and the majority of content is imagery. The only significant changes were updating the footer to what we discussed and simplifying the header / removing subnav.

**Comment by NinaTanneberger** [comment]
> I've been troubleshooting the install_v4 issue with you.
> In terms of the home page, with no solution being found by the team or @rhaubt I've resorted to a plain background and without images there has been little change as I've been following the `Mock_Home2.png` mock-up and the majority of content is imagery. The only significant changes were updating the footer to what we discussed and simplifying the header / removing subnav.

Cool. Have you started playing with the templates yet? Also did **front end** decide to scrap the nav bar? I remember there being one earlier.

**Comment by NinaTanneberger** [comment]
@JacksonGartner have you read this [page](https://www.mediawiki.org/wiki/Manual:Linked_images)

**Comment by JacksonGartner** [comment]
No I haven't downloaded the templates yet, I was unaware they were ready. I'll continue to work on the home page tomorrow and make it as best I can. And yes, we decided to scrap the navbar.

**Comment by jbren48** [comment]
I have been helping you try to figure out the Clean Install so I can move onto the Infobox task that was given to me, due to this I have not been able to do much progress without the clean install, I have also done a basic template for the Display Page so that we can test the Templates on our machines, this is not completed unfortunately because the Media Wiki isn't working.

**Comment by NinaTanneberger** [comment]
@jbren48 in order to help you with the install you need to communicate with me, I was not aware of this at all this week. @JacksonGartner the templates are the Site Pages folder. 

Since the install isn't working, I have put a folder in the repository called installFailsafe. Check it out and read the README.txt

**Comment by NinaTanneberger** [comment]
[Video](https://www.youtube.com/watch?v=Wp9dbyZa3XA&feature=youtu.be)  for my xampp and repository install

**Comment by jbren48** [comment]
I have been communicating with you. I tried to get the extension working on my own machine without the clean install because I knew it wasn't working, so I reached out on the Saturday for help just like we discussed in the lecture. You then said to me I need the clean install with all the extensions on GitHub. 

> Yes because you are meant to download the repository that I created on GitHub with all the extension installs. See the Clean Install MediaWiki issue.

But the clean install isn't working on my machine, I have been uploading comments and have been trying my best to communicate with you so that we can fix this issue so I can get the InfoBox task done because we discussed how important it was. My apologies if thinking this was a priority was incorrect.

Will follow the video for install and let you know

**Comment by jbren48** [comment]
The database is now working, the only thing I did differently is renamed the LocalSettings.php instead of removing it and putting it back.

**Comment by NinaTanneberger** [comment]
And that is the only communication I had with you, you did not reply to my comment or say that you were having difficult.

**Comment by GaryLamKa** [comment]
Sorry for disappear for the whole week, the clean install is working fine, the awesome youtube video helped alot and i will update the templates tonight
